;;; pine-script-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from pine-script-mode.el

(autoload 'pine-script-mode "pine-script-mode"
"A major mode for editing TradingView Pine Script v6 files.

In addition to any hooks its parent mode `prog-mode' might have run,
this mode runs the hook `pine-script-mode-hook', as the final or
penultimate step during initialization.

\\{pine-script-mode-map}" t)
(add-to-list 'auto-mode-alist '("\\.pine\\'" . pine-script-mode))
(add-to-list 'auto-mode-alist '("\\.pinescript\\'" . pine-script-mode))
(register-definition-prefixes "pine-script-mode" '("pine-script-"))

;;; End of scraped data

(provide 'pine-script-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; pine-script-mode-autoloads.el ends here
